kind: Service
apiVersion: v1
metadata:
  name: kafka-manager
  namespace: kafka-prod
spec:
  type: NodePort
  selector:
    app: kafka-manager
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
