apiVersion: v1
kind: Service
metadata:
  name: kafka-manager
  namespace: kafka
spec:
  ports:
  - name: kafka-manager-port
    port: 80
    targetPort: 9000
  type: NodePort
  selector:
    app: kafka-manager



