apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-manager
  namespace: kafka
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kafka-manager
    spec:
      nodeSelector:
        "cloud.google.com/gke-nodepool": dev-pool
      containers:
      - name: kafka-manager
        image: supersoftware/kafka-manager
        ports:
        - containerPort: 9000
        env:
        - name: ZK_HOSTS
          value: zookeeper:2181
        - name: APPLICATION_SECRET
          value: admin
        - name: KM_ARGS
          value: -Djava.net.preferIPv4Stack=true
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /
            port: 9000
