# A headless service to create DNS records
---
apiVersion: v1
kind: Service
metadata:
  name: broker
  namespace: kafka-prod
spec:
  ports:
  - port: 9092
  # [podname].broker.kafka-prod.svc.cluster.local
  clusterIP: None
  selector:
    app: kafka
